title: JustMyFreedom
email: justmyfreedom@outlook.com
description: 成功只有一种，那就是按照自己喜欢的方式过完一生。
url: https://justmyfreedom.com/
theme: null

# 网站输出目录
destination: _site

## => Author and Social
author:
  name: JustMyFreedom
  email: justmyfreedom@outlook.com

readme_index:
  with_frontmatter: true

# 指定使用的 Jekyll 插件，如果需要自己编写插件，需要放在 _plugins 目录下。
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# include：指定 Jekyll 处理的文件或目录
# include:
#   - /blog


# 指定 Jekyll 忽略的文件或目录
exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

# 项目版本
docs:
  build_revision: '1.0.0'

# 搜索框文本
search:
  description: search


# 七牛配置
qiniu:
  img_url: https://image.justmyfreedom.com/