title: JustMyFreedom
email: justmyfreedom@outlook.com
description: 成功只有一种，那就是按照自己喜欢的方式过完一生。
url: http://justmyfreedom.com/
theme: null
# baseurl: / # 网站根目录，如果你的网站部署在域名下的子目录，需要设置此项。
# paginate：设置分页，可以设置每页显示的文章数量
# timezone：时区，用于生成正确的日期时间戳

## => Paths 访问路径
# paths:
#   root: /
#   home: /blog
#   archive: /blog/archive.html
#   # rss:  /feed.xml


## => Author and Social
##############################
author:
  name: JustMyFreedom
  email: justmyfreedom@outlook.com
  # twitter: kitian616
  # github:  kitian616
  # googleplus: 101827554735084402671
  # weibo: 234695683
  # douban: kitian616

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

# 指定使用的 Jekyll 插件，如果需要自己编写插件，需要放在 _plugins 目录下。
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# include：指定 Jekyll 处理的文件或目录

# 指定 Jekyll 忽略的文件或目录
exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

# 项目版本
docs:
  build_revision: '1.0.0'

# 搜索框文本
search:
  description: search


# 七牛配置
qiniu:
  img_url: https://image.justmyfreedom.com/